# use official ubuntu runtime as parent image
    #server version of ubuntu = 18.04
FROM ubuntu:18.04
ADD ./hello-world.sh ~/hello-world.sh

# Run hello-world.sh when the container launches
CMD ["~/hello-world.sh"]
